#!/data/data/com.termux/files/usr/bin/python

import sys

if len(sys.argv) < 2:
    print("Uso: a archivo.a")
    exit()

file = sys.argv[1]

with open(file, "r") as f:
    code = f.read()

exec(code)
